export type DocRequirement = 'required' | 'conditional' | 'optional'

export type DocPhase = 'pre_contract' | 'under_contract' | 'closing'

export interface TNDocumentSlot {
  id: string
  display_name: string
  document_type: string
  phase: DocPhase
  requirement: DocRequirement
  condition?: string
  reva_note?: string
  why_it_matters?: string
}

export const TN_DOCUMENT_CHECKLIST: TNDocumentSlot[] = [
  {
    id: 'buyer_rep',
    display_name: 'Buyer Representation Agreement (RF141)',
    document_type: 'rf621_buyer_rep',
    phase: 'pre_contract',
    requirement: 'required',
    reva_note: 'Check expiration date, agency type, and all signatures. This is your legal authority to represent the buyer.',
    why_it_matters: 'Without this, you have no legal representation agreement. This protects you and your buyer.',
  },
  {
    id: 'working_with_pro',
    display_name: 'Working with a Real Estate Professional',
    document_type: 'working_with_pro',
    phase: 'pre_contract',
    requirement: 'required',
    reva_note: 'Verify buyer signature and date. Must be provided before any real estate services.',
    why_it_matters: 'Tennessee law requires this disclosure. Missing it is a license violation.',
  },
  {
    id: 'disclaimer_notice',
    display_name: 'Disclaimer Notice',
    document_type: 'disclaimer_notice',
    phase: 'pre_contract',
    requirement: 'required',
    reva_note: 'Verify all parties signed. Must be acknowledged before offer.',
    why_it_matters: 'Required by TCA 62-13. Protects agent from liability claims.',
  },
  {
    id: 'wire_fraud_pre',
    display_name: 'Wire Fraud Warning',
    document_type: 'wire_fraud_warning',
    phase: 'pre_contract',
    requirement: 'required',
    reva_note: 'Check buyer initials. Wire fraud is the #1 real estate scam in TN.',
    why_it_matters: 'One wire fraud incident can cost a buyer their entire down payment. This is your protection too.',
  },
  {
    id: 'written_agreement_tour',
    display_name: 'Written Agreement Before Touring a Home',
    document_type: 'written_agreement_tour',
    phase: 'pre_contract',
    requirement: 'conditional',
    condition: 'Required if buyer toured homes before signing Buyer Rep Agreement',
    reva_note: 'Check tour dates align with agreement dates.',
    why_it_matters: 'NAR settlement requirement. Protects your compensation if buyer toured before signing rep agreement.',
  },
  {
    id: 'buyer_rep_amendment',
    display_name: 'Amendment to Buyer Representation Agreement',
    document_type: 'buyer_rep_amendment',
    phase: 'pre_contract',
    requirement: 'conditional',
    condition: 'Required if any terms of the Buyer Rep Agreement were changed',
    reva_note: 'Check what terms changed and new expiration date.',
    why_it_matters: 'Any change to the rep agreement must be in writing or the original terms control.',
  },
  {
    id: 'binder_receipt',
    display_name: 'Binder / Trust Money Receipt',
    document_type: 'binder_receipt',
    phase: 'under_contract',
    requirement: 'optional',
    reva_note: 'Verify amount matches PSA Section 3.',
    why_it_matters: 'Documents receipt of earnest money. Protects all parties if dispute arises over deposit.',
  },
  {
    id: 'binder_request',
    display_name: 'Binder / Trust Money Request',
    document_type: 'binder_request',
    phase: 'under_contract',
    requirement: 'optional',
    reva_note: 'Track if request was sent and when earnest money is due.',
    why_it_matters: 'Creates paper trail for earnest money collection timeline.',
  },
  {
    id: 'compensation_agreement',
    display_name: 'Compensation Agreement',
    document_type: 'compensation_agreement',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required when seller is paying buyer agent compensation',
    reva_note: 'Verify compensation amount matches what was negotiated.',
    why_it_matters: 'Post-NAR settlement, this is how buyer agent comp is documented in the transaction.',
  },
  {
    id: 'rf401_psa',
    display_name: 'Purchase & Sale Agreement (RF401)',
    document_type: 'rf401_psa',
    phase: 'under_contract',
    requirement: 'required',
    reva_note: 'Full extraction: price, dates, contingencies, loan type, all signatures. Run full broker review.',
    why_it_matters: 'This is the contract. Every other document flows from this.',
  },
  {
    id: 'counter_offer',
    display_name: 'Counter Offer (RF406)',
    document_type: 'rf406_counter',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required if seller or buyer countered the original offer',
    reva_note: 'Check which terms changed. Update master deal price/dates.',
    why_it_matters: 'A countered offer is a new contract. Missing this creates liability if a dispute arises.',
  },
  {
    id: 'addendum',
    display_name: 'Addendum',
    document_type: 'addendum',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required when additional terms are added to PSA',
    reva_note: 'Extract all additional terms and flag any that conflict with PSA.',
    why_it_matters: 'Addenda modify the PSA and must be tracked carefully.',
  },
  {
    id: 'amendment',
    display_name: 'Amendment (RF407)',
    document_type: 'rf407_amendment',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required if any terms were changed after binding',
    reva_note: 'Apply date/price changes to master deal timeline.',
    why_it_matters: 'All changes to an executed contract must be in writing or they are unenforceable.',
  },
  {
    id: 'fha_va_addendum',
    display_name: 'FHA / VA Addendum (RF625)',
    document_type: 'fha_addendum',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required when loan type is FHA or VA — check PSA Section 2A',
    reva_note: 'Verify escape clause, amendatory clause, and appraised value.',
    why_it_matters: 'FHA/VA loans have specific protections. Missing this addendum can void the loan.',
  },
  {
    id: 'confirmation_agency',
    display_name: 'Confirmation of Agency (RF302)',
    document_type: 'confirmation_agency',
    phase: 'under_contract',
    requirement: 'required',
    reva_note: 'Verify correct agency type checked and all parties signed.',
    why_it_matters: 'Tennessee law requires agency disclosure at contract. Missing this is a violation.',
  },
  {
    id: 'agency_change_notice',
    display_name: 'Notification of Change of Agency Status',
    document_type: 'agency_change_notice',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required if agency status changed during the transaction',
    reva_note: 'Verify new agency status and all signatures.',
    why_it_matters: 'Agency changes mid-transaction must be disclosed. Failure is a TREC violation.',
  },
  {
    id: 'property_condition',
    display_name: 'Property Condition Disclosure (RF201)',
    document_type: 'property_condition',
    phase: 'under_contract',
    requirement: 'required',
    reva_note: 'Flag any YES answers in Section B or C. Check seller name matches PSA.',
    why_it_matters: 'Sellers are required by TCA 66-5-201. Buyers deserve to know the condition.',
  },
  {
    id: 'inspection_importance',
    display_name: 'Importance of Getting a Home Inspection',
    document_type: 'inspection_importance',
    phase: 'under_contract',
    requirement: 'required',
    reva_note: 'Verify buyer signature. Must be provided before inspection period expires.',
    why_it_matters: 'Protects you from liability if buyer waives inspection and later finds problems.',
  },
  {
    id: 'septic_importance',
    display_name: 'Importance of a Property Septic Inspection',
    document_type: 'septic_importance',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required when property has septic system',
    reva_note: 'Check buyer acknowledgment and septic permit disclosure.',
    why_it_matters: 'Septic system failures are expensive. Carter, Johnson, Washington counties have many rural septic properties.',
  },
  {
    id: 'lead_paint',
    display_name: 'Lead Based Paint Disclosure',
    document_type: 'lead_paint',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Federally required if property was built before 1978',
    reva_note: 'Check year built on PSA. Verify buyer acknowledgment and 10-day inspection window.',
    why_it_matters: 'Federal law. Failure to provide this is a federal violation — not just a state issue.',
  },
  {
    id: 'lead_paint_pamphlet',
    display_name: 'Protect Your Family from Lead Pamphlet',
    document_type: 'lead_paint_pamphlet',
    phase: 'under_contract',
    requirement: 'optional',
    condition: 'Recommended for pre-1978 properties',
    reva_note: 'EPA required pamphlet. Goes with lead paint disclosure.',
    why_it_matters: 'Required alongside Lead Paint Disclosure for pre-1978 properties. Most agents forget this piece.',
  },
  {
    id: 'personal_interest',
    display_name: 'Personal Interest Disclosure and Consent',
    document_type: 'personal_interest',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required if agent has personal interest in the property',
    reva_note: 'Verify disclosure is complete and buyer has consented.',
    why_it_matters: 'If you or a family member is involved in the transaction, this protects your license.',
  },
  {
    id: 'subsurface_sewage',
    display_name: 'Subsurface Sewage Disposal System Permit Disclosure',
    document_type: 'subsurface_sewage',
    phase: 'under_contract',
    requirement: 'optional',
    reva_note: 'Verify permit number, bedroom count, and system type.',
    why_it_matters: 'Tennessee requires this for properties with septic. Buyers need to know permitted bedroom count.',
  },
  {
    id: 'water_waste',
    display_name: 'Water Supply and Waste Disposal Notification',
    document_type: 'water_waste',
    phase: 'under_contract',
    requirement: 'optional',
    reva_note: 'Check water source type matches property condition disclosure.',
    why_it_matters: 'Rural TN properties often have wells and septic. Buyers need full picture.',
  },
  {
    id: 'repair_proposal',
    display_name: 'Repair Proposal',
    document_type: 'repair_proposal',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required when buyer requests repairs after inspection',
    reva_note: 'Check items requested match inspection report findings.',
    why_it_matters: 'Documents what was requested. Protects buyer if seller fails to complete repairs.',
  },
  {
    id: 'repair_amendment',
    display_name: 'Repair / Replacement Amendment',
    document_type: 'repair_amendment',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required when repairs were negotiated and agreed to',
    reva_note: 'Check repair deadline, who is responsible, and completion requirement.',
    why_it_matters: 'Without this signed document, the seller has no legal obligation to make repairs.',
  },
  {
    id: 'buyer_repair_auth',
    display_name: 'Buyer Authorization for Pre-Closing Repairs',
    document_type: 'buyer_repair_auth',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required if buyer is authorized to make repairs before closing',
    reva_note: 'Verify scope, liability provisions, and completion deadline.',
    why_it_matters: 'Without this, buyer entering property before closing for repairs is a liability nightmare.',
  },
  {
    id: 'notification',
    display_name: 'Notification Form',
    document_type: 'notification',
    phase: 'under_contract',
    requirement: 'optional',
    reva_note: 'Track what notifications were sent and when.',
    why_it_matters: 'Creates paper trail for all formal notices between parties. Important if deal falls apart.',
  },
  {
    id: 'fsbo_agreement',
    display_name: 'Agreement to Show Property (FSBO)',
    document_type: 'fsbo_agreement',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required when property is For Sale By Owner',
    reva_note: 'Verify compensation terms and showing authorization.',
    why_it_matters: 'Protects your compensation when working with FSBO sellers who have no listing agent.',
  },
  {
    id: 'inspection_report',
    display_name: 'Inspection Report',
    document_type: 'inspection_report',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required when inspection was performed',
    reva_note: 'Flag major defects, safety items, and anything that could affect financing.',
    why_it_matters: 'The inspection report drives everything in the resolution period.',
  },
  {
    id: 'termination_notice',
    display_name: 'Notice of Termination of Contract',
    document_type: 'termination_notice',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required if contract was terminated',
    reva_note: 'Verify termination basis and earnest money disposition.',
    why_it_matters: 'Proper termination notice is required to release earnest money and avoid default claims.',
  },
  {
    id: 'mutual_release',
    display_name: 'Mutual Release and Disbursement of Earnest Money',
    document_type: 'mutual_release',
    phase: 'under_contract',
    requirement: 'conditional',
    condition: 'Required if contract terminated and earnest money disputed',
    reva_note: 'Verify all parties signed and disbursement instructions are clear.',
    why_it_matters: 'Without this, the holder cannot release earnest money. Both parties must sign.',
  },
  {
    id: 'property_condition_update',
    display_name: 'Residential Property Condition Update',
    document_type: 'property_condition_update',
    phase: 'closing',
    requirement: 'required',
    reva_note: 'Verify no new defects. Compare to original disclosure.',
    why_it_matters: 'Seller must update disclosure if anything changed since original. Protects buyer at closing.',
  },
  {
    id: 'final_walkthrough',
    display_name: 'Buyer Final Walkthrough / Inspection',
    document_type: 'final_walkthrough',
    phase: 'closing',
    requirement: 'required',
    reva_note: 'Check date is within 2 days of closing. Verify condition matches binding date.',
    why_it_matters: 'Buyer has right to verify property condition before closing. Skipping this is risky.',
  },
  {
    id: 'closing_date_amendment',
    display_name: 'Closing Date Amendment',
    document_type: 'closing_date_amendment',
    phase: 'closing',
    requirement: 'conditional',
    condition: 'Required if closing date was extended from original PSA',
    reva_note: 'Verify new date and that all parties signed before original closing date passed.',
    why_it_matters: 'A missed closing date without a signed amendment puts the buyer in default.',
  },
  {
    id: 'closing_disclosure',
    display_name: 'Closing Disclosure (HUD/ALTA Statement)',
    document_type: 'closing_disclosure',
    phase: 'closing',
    requirement: 'required',
    reva_note: 'Compare cash to close against PSA estimates. Flag large variances.',
    why_it_matters: 'Buyer must receive CD 3 business days before closing. Lender requirement.',
  },
  {
    id: 'escrow_agreement',
    display_name: 'Escrow Agreement',
    document_type: 'escrow_agreement',
    phase: 'closing',
    requirement: 'conditional',
    condition: 'Required if repairs or credits are held in escrow post-closing',
    reva_note: 'Verify escrow amount, conditions for release, and deadline.',
    why_it_matters: 'Post-closing escrows without a written agreement become he-said-she-said disputes.',
  },
  {
    id: 'termite_letter',
    display_name: 'Termite / WDI Inspection Letter',
    document_type: 'termite_letter',
    phase: 'closing',
    requirement: 'conditional',
    condition: 'Required for FHA/VA loans — check PSA loan type',
    reva_note: 'Check clearance date is within 30 days of closing. Must show no active infestation.',
    why_it_matters: 'FHA/VA will not close without a clear termite letter. Getting this late kills closing dates.',
  },
  {
    id: 'temp_occupancy_buyer',
    display_name: 'Temporary Occupancy Agreement — Buyer Before Closing',
    document_type: 'temp_occupancy_buyer',
    phase: 'closing',
    requirement: 'conditional',
    condition: 'Required if buyer takes possession before closing date',
    reva_note: 'Verify daily rate, liability provisions, and insurance requirements.',
    why_it_matters: 'Buyer living in property before closing without this agreement is a massive liability for the seller.',
  },
  {
    id: 'temp_occupancy_seller',
    display_name: 'Temporary Occupancy Agreement — Seller After Closing',
    document_type: 'temp_occupancy_seller',
    phase: 'closing',
    requirement: 'conditional',
    condition: 'Required if seller remains in property after closing date',
    reva_note: 'Verify daily rate, end date, deposit amount, and what happens if seller does not vacate.',
    why_it_matters: 'Sellers who overstay without this agreement become tenants. Extremely difficult to remove.',
  },
  {
    id: 'referral_agreement',
    display_name: 'Referral Agreement',
    document_type: 'referral_agreement',
    phase: 'closing',
    requirement: 'conditional',
    condition: 'Required if transaction involves a referral fee to another agent/broker',
    reva_note: 'Verify referral percentage and paying party.',
    why_it_matters: 'Referral fees without a written agreement are unenforceable and create brokerage liability.',
  },
  {
    id: 'referring_w9',
    display_name: 'Referring Agent Brokerage W-9',
    document_type: 'referring_w9',
    phase: 'closing',
    requirement: 'conditional',
    condition: 'Required when referral fee is being paid at closing',
    reva_note: 'Must be on file before closing agent can disburse referral fee.',
    why_it_matters: 'Title company cannot pay a referral without a W-9 on file. This holds up closing disbursements.',
  },
]

export function getSlotsByPhase(phase: DocPhase): TNDocumentSlot[] {
  return TN_DOCUMENT_CHECKLIST.filter((s) => s.phase === phase)
}

export function matchDocToSlot(document_type: string): TNDocumentSlot | undefined {
  return TN_DOCUMENT_CHECKLIST.find((s) => s.document_type === document_type)
}
