export type FormField = { id: string; label: string; type: 'text' | 'date' | 'number' | 'select' | 'checkbox' | 'signature'; required: boolean; placeholder?: string; options?: string[]; aiHint?: string; };
export type TRECForm = { id: string; code: string; name: string; shortName: string; version: string; pages: number; category: 'compensation' | 'lease' | 'purchase' | 'application'; description: string; fields: FormField[]; };

export const TREC_FORMS: TRECForm[] = [
  {
    id: 'rf702',
    code: 'RF702',
    name: 'Compensation Agreement Between Listing & Buyer Broker',
    shortName: 'Compensation Agreement',
    version: '1.0',
    pages: 1,
    category: 'compensation',
    description: 'Agreement outlining compensation between listing and buyer brokers.',
    fields: [
      { id: 'agreementDate', label: 'Agreement Date', type: 'date', required: true, aiHint: '' },
      { id: 'propertyAddress', label: 'Property Address', type: 'text', required: true, aiHint: 'Use active transaction property address' },
      { id: 'buyerName', label: 'Buyer Name', type: 'text', required: true, aiHint: 'Use buyer name from transaction' },
      { id: 'listingBrokerFirmName', label: 'Listing Broker Firm Name', type: 'text', required: true, aiHint: "iHome-KW Kingsport" },
      { id: 'listingFirmAddress', label: 'Listing Firm Address', type: 'text', required: false },
      { id: 'buyerBrokerFirmName', label: 'Buyer Broker Firm Name', type: 'text', required: false },
      { id: 'buyerBrokerFirmAddress', label: 'Buyer Broker Firm Address', type: 'text', required: false },
      { id: 'compensationAmount', label: 'Compensation Amount', type: 'number', required: false },
      { id: 'compensationPercent', label: 'Compensation Percent', type: 'number', required: false },
      { id: 'specialStipulations', label: 'Special Stipulations', type: 'text', required: false },
      { id: 'listingBrokerSignature', label: 'Listing Broker Signature', type: 'signature', required: false },
      { id: 'listingBrokerDate', label: 'Listing Broker Date', type: 'date', required: false },
      { id: 'listingBrokerPhone', label: 'Listing Broker Phone', type: 'text', required: false },
      { id: 'listingBrokerEmail', label: 'Listing Broker Email', type: 'text', required: false },
      { id: 'buyerBrokerSignature', label: 'Buyer Broker Signature', type: 'signature', required: false },
      { id: 'buyerBrokerDate', label: 'Buyer Broker Date', type: 'date', required: false },
      { id: 'buyerBrokerPhone', label: 'Buyer Broker Phone', type: 'text', required: false },
      { id: 'buyerBrokerEmail', label: 'Buyer Broker Email', type: 'text', required: false },
    ]
  },
  {
    id: 'rf421',
    code: 'RF421',
    name: 'Residential Lease Agreement for Single-Family Dwelling',
    shortName: 'Residential Lease',
    version: '1.0',
    pages: 10,
    category: 'lease',
    description: 'Standard lease agreement for single-family dwellings.',
    fields: [
      { id: 'tenantName', label: 'Tenant Name', type: 'text', required: true },
      { id: 'landlordName', label: 'Landlord Name', type: 'text', required: true },
      { id: 'propertyAddress', label: 'Property Address', type: 'text', required: true, aiHint: 'Use active transaction property address' },
      { id: 'city', label: 'City', type: 'text', required: false },
      { id: 'zip', label: 'ZIP', type: 'text', required: false },
      { id: 'leaseTerm', label: 'Lease Term', type: 'text', required: false },
      { id: 'leaseStartDate', label: 'Lease Start Date', type: 'date', required: false },
      { id: 'leaseEndDate', label: 'Lease End Date', type: 'date', required: false },
      { id: 'monthlyRent', label: 'Monthly Rent', type: 'number', required: false },
      { id: 'lateFee', label: 'Late Fee', type: 'text', required: false },
      { id: 'securityDepositAmount', label: 'Security Deposit Amount', type: 'number', required: false },
      { id: 'securityDepositHolder', label: 'Security Deposit Holder', type: 'text', required: false },
      { id: 'leadBasedPaint', label: 'Lead Based Paint Disclosure', type: 'checkbox', required: false },
      { id: 'tenantInsuranceAmount', label: 'Tenant Insurance Amount', type: 'number', required: false },
      { id: 'holdoverNoticeDays', label: 'Holdover Notice Days', type: 'number', required: false },
      { id: 'holdoverRent', label: 'Holdover Rent', type: 'number', required: false },
      { id: 'specialStipulations', label: 'Special Stipulations', type: 'text', required: false },
    ]
  },
  {
    id: 'rf403',
    code: 'RF403',
    name: 'New Construction Purchase and Sale Agreement',
    shortName: 'New Construction PSA',
    version: '1.0',
    pages: 12,
    category: 'purchase',
    description: 'Purchase agreement for new construction homes.',
    fields: [
      { id: 'buyerName', label: 'Buyer Name', type: 'text', required: true, aiHint: 'Use buyer name from transaction' },
      { id: 'sellerName', label: 'Seller Name', type: 'text', required: true },
      { id: 'propertyAddress', label: 'Property Address', type: 'text', required: true, aiHint: 'Use active transaction property address' },
      { id: 'city', label: 'City', type: 'text', required: false },
      { id: 'zip', label: 'ZIP', type: 'text', required: false },
      { id: 'county', label: 'County', type: 'text', required: false },
      { id: 'purchasePrice', label: 'Purchase Price', type: 'number', required: true },
      { id: 'loanType', label: 'Loan Type', type: 'select', options: ['Conventional','FHA','VA','Other'], required: false },
      { id: 'loanAmount', label: 'Loan Amount', type: 'number', required: false },
      { id: 'closingDate', label: 'Closing Date', type: 'date', required: false, aiHint: 'Calculate from transaction timeline' },
      { id: 'earnestMoneyAmount', label: 'Earnest Money Amount', type: 'number', required: false },
      { id: 'earnestMoneyHolder', label: 'Earnest Money Holder', type: 'text', required: false },
      { id: 'inspectionMethod', label: 'Inspection Method', type: 'select', options: ['Punch List','Traditional'], required: false },
      { id: 'inspectionDays', label: 'Inspection Days', type: 'number', required: false },
      { id: 'associationFeeType', label: 'Association Fee Type', type: 'select', options: ['Mandatory','Not Mandatory','No Association'], required: false },
      { id: 'specialStipulations', label: 'Special Stipulations', type: 'text', required: false },
    ]
  },
  {
    id: 'rf404',
    code: 'RF404',
    name: 'Lot/Land Purchase and Sale Agreement',
    shortName: 'Lot/Land PSA',
    version: '1.0',
    pages: 10,
    category: 'purchase',
    description: 'Agreement for purchase of lot or land.',
    fields: [
      { id: 'buyerName', label: 'Buyer Name', type: 'text', required: true },
      { id: 'sellerName', label: 'Seller Name', type: 'text', required: true },
      { id: 'propertyAddress', label: 'Property Address', type: 'text', required: true, aiHint: 'Use active transaction property address' },
      { id: 'city', label: 'City', type: 'text', required: false },
      { id: 'zip', label: 'ZIP', type: 'text', required: false },
      { id: 'county', label: 'County', type: 'text', required: false },
      { id: 'purchasePrice', label: 'Purchase Price', type: 'number', required: true },
      { id: 'pricingBasis', label: 'Pricing Basis', type: 'select', options: ['per tract','per acre','per acre adjusted'], required: false },
      { id: 'loanType', label: 'Loan Type', type: 'text', required: false },
      { id: 'loanAmount', label: 'Loan Amount', type: 'number', required: false },
      { id: 'closingDate', label: 'Closing Date', type: 'date', required: false },
      { id: 'earnestMoneyAmount', label: 'Earnest Money Amount', type: 'number', required: false },
      { id: 'greenbeltIntent', label: 'Greenbelt Intent', type: 'select', options: ['maintain','do not maintain'], required: false },
      { id: 'feasibilityStudyDays', label: 'Feasibility Study Days', type: 'number', required: false },
      { id: 'specialStipulations', label: 'Special Stipulations', type: 'text', required: false },
    ]
  },
  {
    id: 'rf631',
    code: 'RF631',
    name: 'Tenant Information Application',
    shortName: 'Tenant Application',
    version: '1.0',
    pages: 2,
    category: 'application',
    description: 'Tenant application for rental screening.',
    fields: [
      { id: 'propertyAddress', label: 'Property Address', type: 'text', required: true, aiHint: 'Use active transaction property address' },
      { id: 'tenantName', label: 'Tenant Name', type: 'text', required: true },
      { id: 'tenantDOB', label: 'Tenant DOB', type: 'date', required: false },
      { id: 'coTenantName', label: 'Co-Tenant Name', type: 'text', required: false },
      { id: 'presentAddress', label: 'Present Address', type: 'text', required: false },
      { id: 'city', label: 'City', type: 'text', required: false },
      { id: 'state', label: 'State', type: 'text', required: false },
      { id: 'zip', label: 'ZIP', type: 'text', required: false },
      { id: 'phone', label: 'Phone', type: 'text', required: false },
      { id: 'email', label: 'Email', type: 'text', required: false },
      { id: 'occupation', label: 'Occupation', type: 'text', required: false },
      { id: 'employer', label: 'Employer', type: 'text', required: false },
      { id: 'monthlyGrossIncome', label: 'Monthly Gross Income', type: 'number', required: false },
      { id: 'bankReference', label: 'Bank Reference', type: 'text', required: false },
      { id: 'personalReference', label: 'Personal Reference', type: 'text', required: false },
      { id: 'evicted', label: 'Evicted Previously', type: 'checkbox', required: false },
      { id: 'bankruptcy', label: 'Bankruptcy', type: 'checkbox', required: false },
    ]
  }
]
