import { FormDefinition } from '../types'

export const RF401_FORM: FormDefinition = {
  id: 'rf401',
  name: 'RF401 – Residential Purchase & Sale Agreement',
  description: 'Phase 21 RF401 workflow for Tennessee agents',
  category: 'purchase',
  defaultStepId: 'select-deal',
  steps: [
    { id: 'select-deal', label: 'Select Deal', fieldIds: ['deal_reference'] },
    { id: 'verify-parties', label: 'Verify Parties', fieldIds: ['buyer_names', 'seller_names'] },
    { id: 'property-price', label: 'Property & Price', fieldIds: ['property_address', 'property_city', 'property_county', 'sale_price', 'earnest_money'] },
    {
      id: 'financing-contingencies',
      label: 'Financing & Contingencies',
      fieldIds: ['financing_type', 'loan_amount', 'loan_rate', 'financing_contingency_date', 'appraisal_deadline', 'inspection_period_days', 'inspection_deadline', 'closing_date'],
    },
    { id: 'stipulations', label: 'Stipulations', fieldIds: ['special_stipulations', 'additional_documents'] },
    { id: 'review-export', label: 'Review & Export', fieldIds: ['review_notes'] },
  ],
  fields: [
    { id: 'deal_reference', label: 'Deal reference', type: 'text', required: true, hint: 'Internal label or MLS number' },
    { id: 'buyer_names', label: 'Buyer(s)', type: 'text', required: true, hint: 'Full legal name(s)' },
    { id: 'seller_names', label: 'Seller(s)', type: 'text', required: true },
    { id: 'property_address', label: 'Property address', type: 'text', required: true },
    { id: 'property_city', label: 'City', type: 'text' },
    { id: 'property_county', label: 'County', type: 'text' },
    { id: 'sale_price', label: 'Sale price ($)', type: 'number', required: true },
    { id: 'earnest_money', label: 'Earnest money ($)', type: 'number' },
    { id: 'closing_date', label: 'Closing date', type: 'date' },
    { id: 'financing_type', label: 'Financing type', type: 'select', options: ['Conventional', 'FHA', 'VA', 'USDA', 'Cash', 'Other'] },
    { id: 'loan_amount', label: 'Loan amount ($)', type: 'number' },
    { id: 'loan_rate', label: 'Loan rate (%)', type: 'number' },
    { id: 'financing_contingency_date', label: 'Financing contingency deadline', type: 'date' },
    { id: 'appraisal_deadline', label: 'Appraisal deadline', type: 'date' },
    { id: 'inspection_period_days', label: 'Inspection period (days)', type: 'number' },
    { id: 'inspection_deadline', label: 'Inspection deadline', type: 'date' },
    { id: 'special_stipulations', label: 'Special stipulations', type: 'textarea', multiLine: true },
    { id: 'additional_documents', label: 'Additional documents/exhibits', type: 'textarea', multiLine: true },
    { id: 'review_notes', label: 'Review notes', type: 'textarea', multiLine: true },
  ],
  autoFillMap: {
    address: 'property_address',
    buyer_names: 'buyer_names',
    seller_names: 'seller_names',
    purchase_price: 'sale_price',
    earnest_money: 'earnest_money',
    closing: 'closing_date',
    financing_contingency_date: 'financing_contingency_date',
    appraisal_deadline: 'appraisal_deadline',
    inspection_end_date: 'inspection_deadline',
  },
}
