export type RF401QuestionType = 'text' | 'currency' | 'number' | 'checkbox' | 'date' | 'datetime' | 'select' | 'multiline'

export interface RF401Question {
  id: string
  rf401Lines: string
  rf401Page: number
  type: RF401QuestionType
  veraQuestion: string
  validates: string
  veraConfirms: string
  veraFlags: string | null
  skipIf?: string // condition string, evaluated at runtime
  dependsOn?: string // question id this depends on
}

export const RF401_INTAKE_SCRIPT: RF401Question[] = [
  {
    id: 'property_address',
    rf401Lines: '6',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "Let's build your RF401. What's the property address — street number and name?",
    validates: 'Non-empty string with street number and name',
    veraConfirms: "Got it — [address]. Line 6 filled.",
    veraFlags: null,
  },
  {
    id: 'property_city',
    rf401Lines: '7',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "What city is the property in?",
    validates: 'Valid Tennessee city name',
    veraConfirms: "[city], Tennessee. Line 7 filled.",
    veraFlags: null,
  },
  {
    id: 'property_zip',
    rf401Lines: '7',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "Zip code?",
    validates: '5-digit zip code',
    veraConfirms: "Zip [zip]. I\'ll resolve the county from that.",
    veraFlags: null,
  },
  {
    id: 'property_county',
    rf401Lines: '8',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "What county is the property in? For example: Washington, Sullivan, Carter, Hawkins, Unicoi.",
    validates: 'Valid Tennessee county name',
    veraConfirms: "[county] County. Line 8 filled.",
    veraFlags: null,
  },
  {
    id: 'deed_book',
    rf401Lines: '8',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "Do you have the deed book and page number? These are on the recorded deed. Your title company can pull them if you don\'t have them — just say skip.",
    validates: 'Text or skip',
    veraConfirms: "Deed book [book], page [page]. Line 8 filled.",
    veraFlags: "If skipped: I\'ll leave deed book and page blank. Make sure your title company fills these in before submitting.",
  },
  {
    id: 'instrument_number',
    rf401Lines: '9',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "What\'s the instrument number? This is stamped on the recorded deed — sometimes on page 1, sometimes at the end. Say skip if you don\'t have it.",
    validates: 'Text or skip',
    veraConfirms: "Instrument number [number]. Line 9 filled.",
    veraFlags: "If skipped: Instrument number left blank. Title company will need to provide this.",
  },
  {
    id: 'buyer_1_name',
    rf401Lines: '3',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "Who is the buyer? Give me their full legal name exactly as it should appear on the deed.",
    validates: 'Full legal name, non-empty',
    veraConfirms: "Buyer 1: [name]. Line 3 filled.",
    veraFlags: "If name sounds like a company or LLC: Is this buyer purchasing as an entity? I\'ll need to note that on the deed line as well.",
  },
  {
    id: 'buyer_2_name',
    rf401Lines: '3',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "Is there a second buyer? If not, just say no.",
    validates: 'Full legal name or no',
    veraConfirms: "Buyer 2: [name]. Line 3 filled.",
    veraFlags: null,
  },
  {
    id: 'seller_1_name',
    rf401Lines: '4',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "Who is the seller? Full legal name.",
    validates: 'Full legal name, non-empty',
    veraConfirms: "Seller 1: [name]. Line 4 filled.",
    veraFlags: null,
  },
  {
    id: 'seller_2_name',
    rf401Lines: '4',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "Second seller? If not, say no.",
    validates: 'Full legal name or no',
    veraConfirms: "Seller 2: [name]. Line 4 filled.",
    veraFlags: null,
  },
  {
    id: 'items_remaining',
    rf401Lines: '23-24',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "Any items staying with the property beyond what\'s already in Section A? Section A already covers built-in appliances, ceiling fans, door openers, and mounted fixtures. Anything extra — like a freestanding fridge, non-built-in microwave, or outdoor furniture the buyer wants included at no cost? Say none if not.",
    validates: 'Free text or none',
    veraConfirms: "Section B noted: [items]. Lines 23-24 filled.",
    veraFlags: "Reminder: if the dishwasher or microwave is not built-in, list it here. Don\'t assume it\'s covered by Section A.",
  },
  {
    id: 'garage_remotes',
    rf401Lines: '17',
    rf401Page: 1,
    type: 'number',
    veraQuestion: "How many garage door remotes? The form requires a minimum number — default is 2.",
    validates: 'Integer greater than 0',
    veraConfirms: "[n] garage remotes. Line 17 filled.",
    veraFlags: null,
  },
  {
    id: 'items_not_remaining',
    rf401Lines: '26-27',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "Anything specifically NOT staying that might look like it conveys? For example a mounted TV, specific light fixture, or decorative item the seller is taking. Say none if not.",
    validates: 'Free text or none',
    veraConfirms: "Section C noted: [items]. Lines 26-27 filled.",
    veraFlags: null,
  },
  {
    id: 'leased_items',
    rf401Lines: '30',
    rf401Page: 1,
    type: 'text',
    veraQuestion: "Any leased items on the property — propane tank, water softener, security system, solar panels? Say none if not.",
    validates: 'Free text or none',
    veraConfirms: "Leased items noted: [items]. Line 30 filled.",
    veraFlags: "If yes: Is the buyer assuming the lease? If not assuming, the box on line 33 must be checked and the seller must pay cancellation fees and remove the items before closing.",
  },
  {
    id: 'purchase_price',
    rf401Lines: '40-41',
    rf401Page: 1,
    type: 'currency',
    veraQuestion: "What\'s the purchase price?",
    validates: 'Positive number',
    veraConfirms: "$[amount] — [Written Words]. Lines 40-41 filled.",
    veraFlags: null,
  },
  {
    id: 'loan_type',
    rf401Lines: '55-58',
    rf401Page: 2,
    type: 'select',
    veraQuestion: "What type of financing — Conventional, FHA, VA, USDA/Rural Development, or Cash?",
    validates: 'One of: Conventional, FHA, VA, USDA, Cash',
    veraConfirms: "[type] checked on line 56.",
    veraFlags: "FHA: Don\'t forget to attach the FHA addendum — required in Section 20. | VA: VA addendum required. VA buyers can pay for the termite letter as of June 2022. | Cash: I\'ll check the financing contingency waiver box in Section 2B.",
  },
  {
    id: 'ltv_percentage',
    rf401Lines: '47',
    rf401Page: 2,
    type: 'number',
    veraQuestion: "What\'s the loan-to-value percentage? FHA with 3.5% down = 96.5% LTV. VA zero down = 100% LTV. Conventional with 20% down = 80% LTV.",
    validates: 'Number between 1 and 100',
    veraConfirms: "[n]% LTV. Line 47 filled.",
    veraFlags: "100% LTV: Confirming VA zero-down scenario. | Over 96.5% on non-VA: Unusual for this loan type — confirm with lender.",
    skipIf: 'loan_type === "Cash"',
  },
  {
    id: 'appraisal_contingency',
    rf401Lines: '103-106',
    rf401Page: 2,
    type: 'select',
    veraQuestion: "Is this offer contingent on the property appraising at or above purchase price? Most financed deals are. Cash offers sometimes waive this. Answer: contingent or not contingent.",
    validates: 'One of: contingent, not contingent',
    veraConfirms: "Appraisal [IS / IS NOT] contingent. Section 2C checked.",
    veraFlags: "Not contingent on a financed loan: Heads up — waiving appraisal contingency on a financed deal is unusual. Buyer accepts risk if property appraises low. Confirm this is intentional.",
  },
  {
    id: 'seller_closing_costs',
    rf401Lines: '153-156',
    rf401Page: 3,
    type: 'text',
    veraQuestion: "Is the seller contributing to closing costs? If yes, how much or what\'s the limit? Say none if not.",
    validates: 'Dollar amount, percentage, or none',
    veraConfirms: "Seller contribution: [amount]. Lines 153-156 filled.",
    veraFlags: "FHA: Seller contribution max is 6% of purchase price. | VA: Seller contribution max is 4% (all concessions included). | Conventional LTV >90%: max 3%. Flag if the amount entered exceeds these limits.",
  },
  {
    id: 'closing_agency',
    rf401Lines: '158-161',
    rf401Page: 3,
    type: 'text',
    veraQuestion: "What title company is handling closing? Give me the name, address, and phone number if you have it.",
    validates: 'Title company name required; address and phone preferred',
    veraConfirms: "[title company] — [address] — [phone]. Filled for both buyer and seller sides.",
    veraFlags: null,
  },
  {
    id: 'earnest_money_amount',
    rf401Lines: '165',
    rf401Page: 4,
    type: 'currency',
    veraQuestion: "How much earnest money?",
    validates: 'Positive dollar amount',
    veraConfirms: "$[amount] earnest money.",
    veraFlags: "Zero or blank: Earnest money amount cannot be zero — this creates a default risk on day 1.",
  },
  {
    id: 'earnest_money_days',
    rf401Lines: '162',
    rf401Page: 4,
    type: 'number',
    veraQuestion: "How many days after the Binding Agreement Date is earnest money due? Tennessee standard is 3 days.",
    validates: 'Integer greater than 0',
    veraConfirms: "Earnest due within [n] days of binding date. Line 162 filled.",
    veraFlags: "Zero or blank: Earnest due date cannot be zero or blank — creates immediate default exposure.",
  },
  {
    id: 'closing_date',
    rf401Lines: '195',
    rf401Page: 4,
    type: 'date',
    veraQuestion: "What\'s the target closing date?",
    validates: 'Valid future date',
    veraConfirms: "Closing date: [Month] [Day], [Year]. Line 195 filled.",
    veraFlags: "Closing within 21 days of today: Short timeline — FHA and VA typically need 30-45 days. Confirm lender can close by this date. | Closing date is a FIRM deadline — it does not roll for weekends or holidays.",
  },
  {
    id: 'possession',
    rf401Lines: '202-204',
    rf401Page: 4,
    type: 'select',
    veraQuestion: "When does the buyer take possession — at closing, or via a temporary occupancy agreement?",
    validates: 'One of: at closing, temporary occupancy',
    veraConfirms: "Possession [at closing / per temporary occupancy agreement].",
    veraFlags: "Temporary occupancy: RF635 Temporary Occupancy Agreement must be attached and listed in Section 20.",
  },
  {
    id: 'deed_names',
    rf401Lines: '258',
    rf401Page: 5,
    type: 'text',
    veraQuestion: "Who should be on the deed? Usually the same as buyer names, but could be a trust, LLC, or different name combination. Say same if it matches the buyer names.",
    validates: 'Full legal names or same',
    veraConfirms: "Deed names: [names]. Line 258 filled.",
    veraFlags: "If different from buyer names: Deed names differ from buyer names — confirm this is intentional and make sure your title company knows before closing.",
  },
  {
    id: 'year_built',
    rf401Lines: '275',
    rf401Page: 6,
    type: 'number',
    veraQuestion: "What year was the property built? Properties built before 1978 require a Lead-Based Paint Disclosure.",
    validates: 'Year between 1800 and current year',
    veraConfirms: "Built [year] — Lead-Based Paint [applies / does not apply]. Line 275 checked.",
    veraFlags: "Pre-1978: Lead-Based Paint Disclosure required — attach RF209 and list it in Section 20.",
  },
  {
    id: 'inspection_period_days',
    rf401Lines: '307',
    rf401Page: 6,
    type: 'number',
    veraQuestion: "How many days for the inspection period? Tri-Cities standard is 15 days.",
    validates: 'Integer greater than 0',
    veraConfirms: "[n]-day inspection period. Line 307 filled.",
    veraFlags: "Under 10 days: Short inspection window — buyer may struggle to schedule all inspections in time, especially WDI report.",
  },
  {
    id: 'resolution_period_days',
    rf401Lines: '325',
    rf401Page: 6,
    type: 'number',
    veraQuestion: "How many days for the resolution period after buyer submits repair requests? Standard is 3 days.",
    validates: 'Integer greater than 0',
    veraConfirms: "[n]-day resolution period. Line 325 filled.",
    veraFlags: null,
  },
  {
    id: 'home_protection_plan',
    rf401Lines: '423-426',
    rf401Page: 8,
    type: 'select',
    veraQuestion: "Home Protection Plan — included or waived? If included, who pays and how much?",
    validates: 'One of: waived, included',
    veraConfirms: "Home Protection Plan [included / waived]. Line 426 checked.",
    veraFlags: "Neither selected: A box MUST be checked — if neither is selected, this section is not part of the agreement. | Agent paying: If the plan comes from agent compensation, your title company must be notified and broker must approve.",
  },
  {
    id: 'special_stipulations',
    rf401Lines: '508-524',
    rf401Page: 10,
    type: 'multiline',
    veraQuestion: "Any special stipulations? These override all other sections if there\'s a conflict. Common examples: seller contribution language, specific repair items, survey requirements, rent-back terms. Say none if not.",
    validates: 'Free text or none',
    veraConfirms: "Special stipulations noted. Section 21 filled.",
    veraFlags: "Avoid vague language like TBD, N/A, negotiable, or etc. — these are unenforceable in Tennessee. Be specific and measurable. Use RF77 pre-approved clauses where possible.",
  },
  {
    id: 'offer_expiration',
    rf401Lines: '527',
    rf401Page: 10,
    type: 'datetime',
    veraQuestion: "When does this offer expire — date and time? Common is 5:00 PM the same day or next business day.",
    validates: 'Valid future date and time',
    veraConfirms: "Offer expires [date] at [time] [AM/PM]. Line 527 filled.",
    veraFlags: "Blank expiration: Offer expiration cannot be blank — any blank is deemed zero, meaning no deadline. This creates risk. | Offer expiration is a FIRM deadline — it does not roll for weekends or holidays.",
  },
]
