import { NextRequest, NextResponse } from 'next/server'
import { getSchema } from '@/lib/formSchemas'

export async function POST(req: NextRequest) {
  try {
    const { formId, fields } = await req.json()

    if (!formId || !fields) {
      return NextResponse.json({ error: 'formId and fields are required' }, { status: 400 })
    }

    const schema = getSchema(formId)
    if (!schema) {
      return NextResponse.json({ error: 'Unknown form' }, { status: 400 })
    }

    // Build PDF content as structured text
    // Using a simple text-based PDF generation approach
    const pdfContent = generatePDFBuffer(schema, fields, formId)

    return new NextResponse(pdfContent, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${formId.toUpperCase()}_DealPilot_${new Date().toISOString().split('T')[0]}.pdf"`,
      },
    })
  } catch (err) {
    console.error('PDF generation error:', err)
    return NextResponse.json({ error: 'Failed to generate PDF' }, { status: 500 })
  }
}

function generatePDFBuffer(
  schema: { name: string; description: string; fields: Array<{ key: string; label: string; type: string; section?: string; required?: boolean }> },
  fields: Record<string, string>,
  formId: string
): Buffer {
  // Minimal valid PDF generation without external dependencies
  // This creates a properly formatted PDF with form data
  const sections = Array.from(new Set(schema.fields.map(f => f.section || 'General')))
  
  let textLines: string[] = []
  textLines.push(schema.name)
  textLines.push(schema.description)
  textLines.push(`Generated by DealPilot TN - ${new Date().toLocaleDateString()}`)
  textLines.push('')
  
  for (const section of sections) {
    const sectionFields = schema.fields.filter(f => (f.section || 'General') === section)
    const filledInSection = sectionFields.filter(f => fields[f.key])
    if (filledInSection.length === 0) continue
    
    textLines.push(`--- ${section} ---`)
    for (const f of filledInSection) {
      textLines.push(`${f.label}: ${fields[f.key]}`)
    }
    textLines.push('')
  }

  // Generate minimal valid PDF
  const content = textLines.join('\n')
  const streamContent = `BT\n/F1 10 Tf\n`
    + textLines.map((line, i) => {
        const y = 750 - (i * 14)
        if (y < 50) return ''
        const escaped = line.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
        const fontSize = line.startsWith('---') ? '10' : line === textLines[0] ? '16' : '10'
        return `1 0 0 1 50 ${y} Tm\n/F1 ${fontSize} Tf\n(${escaped}) Tj\n`
      }).join('')
    + 'ET\n'

  const objects: string[] = []
  let xrefOffsets: number[] = []
  let currentOffset = 0

  // PDF Header
  const header = '%PDF-1.4\n'
  currentOffset = header.length

  // Object 1: Catalog
  xrefOffsets.push(currentOffset)
  const obj1 = '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n'
  objects.push(obj1)
  currentOffset += obj1.length

  // Object 2: Pages
  xrefOffsets.push(currentOffset)
  const obj2 = '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n'
  objects.push(obj2)
  currentOffset += obj2.length

  // Object 3: Page
  xrefOffsets.push(currentOffset)
  const obj3 = '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>\nendobj\n'
  objects.push(obj3)
  currentOffset += obj3.length

  // Object 4: Stream content
  xrefOffsets.push(currentOffset)
  const obj4 = `4 0 obj\n<< /Length ${streamContent.length} >>\nstream\n${streamContent}endstream\nendobj\n`
  objects.push(obj4)
  currentOffset += obj4.length

  // Object 5: Font
  xrefOffsets.push(currentOffset)
  const obj5 = '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n'
  objects.push(obj5)
  currentOffset += obj5.length

  // XRef table
  const xrefOffset = currentOffset
  let xref = `xref\n0 6\n0000000000 65535 f \n`
  for (const offset of xrefOffsets) {
    xref += `${String(offset).padStart(10, '0')} 00000 n \n`
  }

  // Trailer
  const trailer = `trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`

  const fullPdf = header + objects.join('') + xref + trailer
  return Buffer.from(fullPdf, 'utf-8')
}
